name: Tests Run

on:
  pull_request:
    branches: [ "main" ]

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build Docker image
        run: docker build -t my-playwright-tests .

      - name: Run tests in Docker
        env:
          STAND_USER: ${{ secrets.STAND_USER }}
          LOCKED_USER: ${{ secrets.LOCKED_USER }}
          PROBLEM_USER: ${{ secrets.PROBLEM_USER }}
          PERF_GLITCH_USER: ${{ secrets.PERF_GLITCH_USER }}
          ERROR_USER: ${{ secrets.ERROR_USER }}
          VISUAL_USER: ${{ secrets.VISUAL_USER }}
          PASSWORD: ${{ secrets.PASSWORD }}
        run: |
          docker run --rm \
            -v "$PWD":/app \
            -w /app \
            -e STAND_USER \
            -e LOCKED_USER \
            -e PROBLEM_USER \
            -e PERF_GLITCH_USER \
            -e ERROR_USER \
            -e VISUAL_USER \
            -e PASSWORD \
            my-playwright-tests \
            pytest --tracing=retain-on-failure

      - name: Upload custom HTML report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: custom-report
          path: result/custom_report.html

      - name: Upload Playwright traces
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: traces
          path: test-results/